


import argparse
import os.path
import sys

import tensorflow as tf

graph_def = tf.GraphDef()
def main(args):
    for event in tf.train.summary_iterator(args.filepath):
        tag = False
        for graph in event.graph_def:
                graph_def.ParseFromString(event.graph_def)
                tag = True
                break
        if tag:
            break
    print ("Graph is loaded")        
    with open(args.output, 'w') as f:
        print (graph_def, file=f)
    print ("Graph is stored in file with protobuf format")   

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument(
      '--filepath',
      type=str,
      required=True,
      help='input event....local file. it is the log file generated by tensorflow for tensorboard.'
  )
  parser.add_argument(
      '--output',
      type=str,
      required=True,
      help='output file path and name.'
  )
  args = parser.parse_args()
  main(args)


